### ISSUE TITLE
<body> and <head> tags aren't rendered when you submit

### ISSUE THREAD

**Issue by cassidoo** [MLH/mlh-no-light#2]
So I wrote my code and did the standard:

```
<!DOCTYPE html>
<html>
<head>
    <title>Document</title>
    ...
</head>
<body>
   ... 
</body>
</html>
```

...but when the page finally rendered, it didn't actually render the `<body>` tag, so when I styled `body { ... }`, none of that showed up. `<head>` wasn't rendered either.

But, all other tags were, so that's what really matters. :)

**Comment by nquinlan** [comment]
Closed by #3
